// Code generated by protoc-gen-go. DO NOT EDIT.
// source: video.proto

package video

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type StreamAccess_ActionType int32

const (
	StreamAccess_PULLUP   StreamAccess_ActionType = 0
	StreamAccess_SENDBACK StreamAccess_ActionType = 1
	StreamAccess_PUSH     StreamAccess_ActionType = 2
	StreamAccess_PLAY     StreamAccess_ActionType = 3
)

var StreamAccess_ActionType_name = map[int32]string{
	0: "PULLUP",
	1: "SENDBACK",
	2: "PUSH",
	3: "PLAY",
}

var StreamAccess_ActionType_value = map[string]int32{
	"PULLUP":   0,
	"SENDBACK": 1,
	"PUSH":     2,
	"PLAY":     3,
}

func (x StreamAccess_ActionType) Enum() *StreamAccess_ActionType {
	p := new(StreamAccess_ActionType)
	*p = x
	return p
}

func (x StreamAccess_ActionType) String() string {
	return proto.EnumName(StreamAccess_ActionType_name, int32(x))
}

func (x *StreamAccess_ActionType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(StreamAccess_ActionType_value, data, "StreamAccess_ActionType")
	if err != nil {
		return err
	}
	*x = StreamAccess_ActionType(value)
	return nil
}

func (StreamAccess_ActionType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0ad4ea8866efb1e3, []int{5, 0}
}

type StreamAccess_AccessControl int32

const (
	StreamAccess_USER         StreamAccess_AccessControl = 0
	StreamAccess_GROUP        StreamAccess_AccessControl = 1
	StreamAccess_COMPANY      StreamAccess_AccessControl = 2
	StreamAccess_COMPANY_TREE StreamAccess_AccessControl = 3
)

var StreamAccess_AccessControl_name = map[int32]string{
	0: "USER",
	1: "GROUP",
	2: "COMPANY",
	3: "COMPANY_TREE",
}

var StreamAccess_AccessControl_value = map[string]int32{
	"USER":         0,
	"GROUP":        1,
	"COMPANY":      2,
	"COMPANY_TREE": 3,
}

func (x StreamAccess_AccessControl) Enum() *StreamAccess_AccessControl {
	p := new(StreamAccess_AccessControl)
	*p = x
	return p
}

func (x StreamAccess_AccessControl) String() string {
	return proto.EnumName(StreamAccess_AccessControl_name, int32(x))
}

func (x *StreamAccess_AccessControl) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(StreamAccess_AccessControl_value, data, "StreamAccess_AccessControl")
	if err != nil {
		return err
	}
	*x = StreamAccess_AccessControl(value)
	return nil
}

func (StreamAccess_AccessControl) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0ad4ea8866efb1e3, []int{5, 1}
}

type GetToken_ActionType int32

const (
	GetToken_PULLUP   GetToken_ActionType = 0
	GetToken_SENDBACK GetToken_ActionType = 1
	GetToken_PUSH     GetToken_ActionType = 2
	GetToken_PLAY     GetToken_ActionType = 3
)

var GetToken_ActionType_name = map[int32]string{
	0: "PULLUP",
	1: "SENDBACK",
	2: "PUSH",
	3: "PLAY",
}

var GetToken_ActionType_value = map[string]int32{
	"PULLUP":   0,
	"SENDBACK": 1,
	"PUSH":     2,
	"PLAY":     3,
}

func (x GetToken_ActionType) Enum() *GetToken_ActionType {
	p := new(GetToken_ActionType)
	*p = x
	return p
}

func (x GetToken_ActionType) String() string {
	return proto.EnumName(GetToken_ActionType_name, int32(x))
}

func (x *GetToken_ActionType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(GetToken_ActionType_value, data, "GetToken_ActionType")
	if err != nil {
		return err
	}
	*x = GetToken_ActionType(value)
	return nil
}

func (GetToken_ActionType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0ad4ea8866efb1e3, []int{6, 0}
}

type Item struct {
	Key                  *string  `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Value                *string  `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Item) Reset()         { *m = Item{} }
func (m *Item) String() string { return proto.CompactTextString(m) }
func (*Item) ProtoMessage()    {}
func (*Item) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ad4ea8866efb1e3, []int{0}
}

func (m *Item) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Item.Unmarshal(m, b)
}
func (m *Item) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Item.Marshal(b, m, deterministic)
}
func (m *Item) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Item.Merge(m, src)
}
func (m *Item) XXX_Size() int {
	return xxx_messageInfo_Item.Size(m)
}
func (m *Item) XXX_DiscardUnknown() {
	xxx_messageInfo_Item.DiscardUnknown(m)
}

var xxx_messageInfo_Item proto.InternalMessageInfo

func (m *Item) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

func (m *Item) GetValue() string {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return ""
}

// 用于封装不同的需要发送到客户端的消息
type RTCMessage struct {
	RtcType              *string  `protobuf:"bytes,1,opt,name=rtcType" json:"rtcType,omitempty"`
	ServiceType          *string  `protobuf:"bytes,2,opt,name=serviceType" json:"serviceType,omitempty"`
	RtcArrayData         []*Item  `protobuf:"bytes,3,rep,name=rtcArrayData" json:"rtcArrayData,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RTCMessage) Reset()         { *m = RTCMessage{} }
func (m *RTCMessage) String() string { return proto.CompactTextString(m) }
func (*RTCMessage) ProtoMessage()    {}
func (*RTCMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ad4ea8866efb1e3, []int{1}
}

func (m *RTCMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RTCMessage.Unmarshal(m, b)
}
func (m *RTCMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RTCMessage.Marshal(b, m, deterministic)
}
func (m *RTCMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RTCMessage.Merge(m, src)
}
func (m *RTCMessage) XXX_Size() int {
	return xxx_messageInfo_RTCMessage.Size(m)
}
func (m *RTCMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_RTCMessage.DiscardUnknown(m)
}

var xxx_messageInfo_RTCMessage proto.InternalMessageInfo

func (m *RTCMessage) GetRtcType() string {
	if m != nil && m.RtcType != nil {
		return *m.RtcType
	}
	return ""
}

func (m *RTCMessage) GetServiceType() string {
	if m != nil && m.ServiceType != nil {
		return *m.ServiceType
	}
	return ""
}

func (m *RTCMessage) GetRtcArrayData() []*Item {
	if m != nil {
		return m.RtcArrayData
	}
	return nil
}

//终端获取本终端使用的视频通道时透传到RTS服务的消息
//uid: 用户唯一标识uid
type GetChannel struct {
	Uid                  *string  `protobuf:"bytes,1,opt,name=uid" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetChannel) Reset()         { *m = GetChannel{} }
func (m *GetChannel) String() string { return proto.CompactTextString(m) }
func (*GetChannel) ProtoMessage()    {}
func (*GetChannel) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ad4ea8866efb1e3, []int{2}
}

func (m *GetChannel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetChannel.Unmarshal(m, b)
}
func (m *GetChannel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetChannel.Marshal(b, m, deterministic)
}
func (m *GetChannel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetChannel.Merge(m, src)
}
func (m *GetChannel) XXX_Size() int {
	return xxx_messageInfo_GetChannel.Size(m)
}
func (m *GetChannel) XXX_DiscardUnknown() {
	xxx_messageInfo_GetChannel.DiscardUnknown(m)
}

var xxx_messageInfo_GetChannel proto.InternalMessageInfo

func (m *GetChannel) GetUid() string {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return ""
}

//RTS服务接收到GetChannel消息后，透传回相应终端的消息
//url: 用户获取的通道地址
type GetChannelResp struct {
	Url                  *string  `protobuf:"bytes,1,opt,name=url" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetChannelResp) Reset()         { *m = GetChannelResp{} }
func (m *GetChannelResp) String() string { return proto.CompactTextString(m) }
func (*GetChannelResp) ProtoMessage()    {}
func (*GetChannelResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ad4ea8866efb1e3, []int{3}
}

func (m *GetChannelResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetChannelResp.Unmarshal(m, b)
}
func (m *GetChannelResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetChannelResp.Marshal(b, m, deterministic)
}
func (m *GetChannelResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetChannelResp.Merge(m, src)
}
func (m *GetChannelResp) XXX_Size() int {
	return xxx_messageInfo_GetChannelResp.Size(m)
}
func (m *GetChannelResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetChannelResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetChannelResp proto.InternalMessageInfo

func (m *GetChannelResp) GetUrl() string {
	if m != nil && m.Url != nil {
		return *m.Url
	}
	return ""
}

// 用于封装Stream的消息
type Stream struct {
	Uid                  *string  `protobuf:"bytes,1,opt,name=uid" json:"uid,omitempty"`
	Url                  *string  `protobuf:"bytes,2,opt,name=url" json:"url,omitempty"`
	Tocken               *string  `protobuf:"bytes,3,opt,name=tocken" json:"tocken,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Stream) Reset()         { *m = Stream{} }
func (m *Stream) String() string { return proto.CompactTextString(m) }
func (*Stream) ProtoMessage()    {}
func (*Stream) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ad4ea8866efb1e3, []int{4}
}

func (m *Stream) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Stream.Unmarshal(m, b)
}
func (m *Stream) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Stream.Marshal(b, m, deterministic)
}
func (m *Stream) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Stream.Merge(m, src)
}
func (m *Stream) XXX_Size() int {
	return xxx_messageInfo_Stream.Size(m)
}
func (m *Stream) XXX_DiscardUnknown() {
	xxx_messageInfo_Stream.DiscardUnknown(m)
}

var xxx_messageInfo_Stream proto.InternalMessageInfo

func (m *Stream) GetUid() string {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return ""
}

func (m *Stream) GetUrl() string {
	if m != nil && m.Url != nil {
		return *m.Url
	}
	return ""
}

func (m *Stream) GetTocken() string {
	if m != nil && m.Tocken != nil {
		return *m.Tocken
	}
	return ""
}

// 用于封装Stream权限的消息
type StreamAccess struct {
	Action               *StreamAccess_ActionType    `protobuf:"varint,1,opt,name=action,enum=video.StreamAccess_ActionType" json:"action,omitempty"`
	Access               *StreamAccess_AccessControl `protobuf:"varint,2,opt,name=access,enum=video.StreamAccess_AccessControl" json:"access,omitempty"`
	Accessuid            *string                     `protobuf:"bytes,3,opt,name=accessuid" json:"accessuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *StreamAccess) Reset()         { *m = StreamAccess{} }
func (m *StreamAccess) String() string { return proto.CompactTextString(m) }
func (*StreamAccess) ProtoMessage()    {}
func (*StreamAccess) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ad4ea8866efb1e3, []int{5}
}

func (m *StreamAccess) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamAccess.Unmarshal(m, b)
}
func (m *StreamAccess) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamAccess.Marshal(b, m, deterministic)
}
func (m *StreamAccess) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamAccess.Merge(m, src)
}
func (m *StreamAccess) XXX_Size() int {
	return xxx_messageInfo_StreamAccess.Size(m)
}
func (m *StreamAccess) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamAccess.DiscardUnknown(m)
}

var xxx_messageInfo_StreamAccess proto.InternalMessageInfo

func (m *StreamAccess) GetAction() StreamAccess_ActionType {
	if m != nil && m.Action != nil {
		return *m.Action
	}
	return StreamAccess_PULLUP
}

func (m *StreamAccess) GetAccess() StreamAccess_AccessControl {
	if m != nil && m.Access != nil {
		return *m.Access
	}
	return StreamAccess_USER
}

func (m *StreamAccess) GetAccessuid() string {
	if m != nil && m.Accessuid != nil {
		return *m.Accessuid
	}
	return ""
}

//终端获取本终端使用的视频tocken时透传到RTS服务的消息
//uid: 用户唯一标识uid
type GetToken struct {
	Uid                  *string  `protobuf:"bytes,1,opt,name=uid" json:"uid,omitempty"`
	Uname                *string  `protobuf:"bytes,2,opt,name=uname" json:"uname,omitempty"`
	Action               *string  `protobuf:"bytes,3,opt,name=action" json:"action,omitempty"`
	Touid                *string  `protobuf:"bytes,4,opt,name=touid" json:"touid,omitempty"`
	Companyid            *string  `protobuf:"bytes,5,opt,name=companyid" json:"companyid,omitempty"`
	Url                  *string  `protobuf:"bytes,6,opt,name=url" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetToken) Reset()         { *m = GetToken{} }
func (m *GetToken) String() string { return proto.CompactTextString(m) }
func (*GetToken) ProtoMessage()    {}
func (*GetToken) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ad4ea8866efb1e3, []int{6}
}

func (m *GetToken) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetToken.Unmarshal(m, b)
}
func (m *GetToken) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetToken.Marshal(b, m, deterministic)
}
func (m *GetToken) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetToken.Merge(m, src)
}
func (m *GetToken) XXX_Size() int {
	return xxx_messageInfo_GetToken.Size(m)
}
func (m *GetToken) XXX_DiscardUnknown() {
	xxx_messageInfo_GetToken.DiscardUnknown(m)
}

var xxx_messageInfo_GetToken proto.InternalMessageInfo

func (m *GetToken) GetUid() string {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return ""
}

func (m *GetToken) GetUname() string {
	if m != nil && m.Uname != nil {
		return *m.Uname
	}
	return ""
}

func (m *GetToken) GetAction() string {
	if m != nil && m.Action != nil {
		return *m.Action
	}
	return ""
}

func (m *GetToken) GetTouid() string {
	if m != nil && m.Touid != nil {
		return *m.Touid
	}
	return ""
}

func (m *GetToken) GetCompanyid() string {
	if m != nil && m.Companyid != nil {
		return *m.Companyid
	}
	return ""
}

func (m *GetToken) GetUrl() string {
	if m != nil && m.Url != nil {
		return *m.Url
	}
	return ""
}

//RTS服务接收到GetTocken消息后，透传回相应终端的消息
//tocken: tocken字符串
type GetTockenResp struct {
	Touid                *string  `protobuf:"bytes,1,opt,name=touid" json:"touid,omitempty"`
	Tocken               *string  `protobuf:"bytes,2,opt,name=tocken" json:"tocken,omitempty"`
	Action               *string  `protobuf:"bytes,3,opt,name=action" json:"action,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTockenResp) Reset()         { *m = GetTockenResp{} }
func (m *GetTockenResp) String() string { return proto.CompactTextString(m) }
func (*GetTockenResp) ProtoMessage()    {}
func (*GetTockenResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ad4ea8866efb1e3, []int{7}
}

func (m *GetTockenResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTockenResp.Unmarshal(m, b)
}
func (m *GetTockenResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTockenResp.Marshal(b, m, deterministic)
}
func (m *GetTockenResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTockenResp.Merge(m, src)
}
func (m *GetTockenResp) XXX_Size() int {
	return xxx_messageInfo_GetTockenResp.Size(m)
}
func (m *GetTockenResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTockenResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetTockenResp proto.InternalMessageInfo

func (m *GetTockenResp) GetTouid() string {
	if m != nil && m.Touid != nil {
		return *m.Touid
	}
	return ""
}

func (m *GetTockenResp) GetTocken() string {
	if m != nil && m.Tocken != nil {
		return *m.Tocken
	}
	return ""
}

func (m *GetTockenResp) GetAction() string {
	if m != nil && m.Action != nil {
		return *m.Action
	}
	return ""
}

//调度台获取视频列表时透传到RTS服务的消息
//uid: 调度台唯一标识uid
type GetStreams struct {
	Uid                  *uint32       `protobuf:"varint,1,opt,name=uid" json:"uid,omitempty"`
	Sa                   *StreamAccess `protobuf:"bytes,2,opt,name=sa" json:"sa,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GetStreams) Reset()         { *m = GetStreams{} }
func (m *GetStreams) String() string { return proto.CompactTextString(m) }
func (*GetStreams) ProtoMessage()    {}
func (*GetStreams) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ad4ea8866efb1e3, []int{8}
}

func (m *GetStreams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStreams.Unmarshal(m, b)
}
func (m *GetStreams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStreams.Marshal(b, m, deterministic)
}
func (m *GetStreams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStreams.Merge(m, src)
}
func (m *GetStreams) XXX_Size() int {
	return xxx_messageInfo_GetStreams.Size(m)
}
func (m *GetStreams) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStreams.DiscardUnknown(m)
}

var xxx_messageInfo_GetStreams proto.InternalMessageInfo

func (m *GetStreams) GetUid() uint32 {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return 0
}

func (m *GetStreams) GetSa() *StreamAccess {
	if m != nil {
		return m.Sa
	}
	return nil
}

//RTS服务接收到GetStreams消息后，透传回相应终端的消息
//tocken: tocken字符串
type GetStreamsResp struct {
	Info                 *GetStreams `protobuf:"bytes,1,opt,name=info" json:"info,omitempty"`
	Stream               []*Stream   `protobuf:"bytes,2,rep,name=stream" json:"stream,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetStreamsResp) Reset()         { *m = GetStreamsResp{} }
func (m *GetStreamsResp) String() string { return proto.CompactTextString(m) }
func (*GetStreamsResp) ProtoMessage()    {}
func (*GetStreamsResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ad4ea8866efb1e3, []int{9}
}

func (m *GetStreamsResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStreamsResp.Unmarshal(m, b)
}
func (m *GetStreamsResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStreamsResp.Marshal(b, m, deterministic)
}
func (m *GetStreamsResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStreamsResp.Merge(m, src)
}
func (m *GetStreamsResp) XXX_Size() int {
	return xxx_messageInfo_GetStreamsResp.Size(m)
}
func (m *GetStreamsResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStreamsResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetStreamsResp proto.InternalMessageInfo

func (m *GetStreamsResp) GetInfo() *GetStreams {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *GetStreamsResp) GetStream() []*Stream {
	if m != nil {
		return m.Stream
	}
	return nil
}

func init() {
	proto.RegisterEnum("video.StreamAccess_ActionType", StreamAccess_ActionType_name, StreamAccess_ActionType_value)
	proto.RegisterEnum("video.StreamAccess_AccessControl", StreamAccess_AccessControl_name, StreamAccess_AccessControl_value)
	proto.RegisterEnum("video.GetToken_ActionType", GetToken_ActionType_name, GetToken_ActionType_value)
	proto.RegisterType((*Item)(nil), "video.Item")
	proto.RegisterType((*RTCMessage)(nil), "video.RTCMessage")
	proto.RegisterType((*GetChannel)(nil), "video.GetChannel")
	proto.RegisterType((*GetChannelResp)(nil), "video.GetChannelResp")
	proto.RegisterType((*Stream)(nil), "video.Stream")
	proto.RegisterType((*StreamAccess)(nil), "video.StreamAccess")
	proto.RegisterType((*GetToken)(nil), "video.GetToken")
	proto.RegisterType((*GetTockenResp)(nil), "video.GetTockenResp")
	proto.RegisterType((*GetStreams)(nil), "video.GetStreams")
	proto.RegisterType((*GetStreamsResp)(nil), "video.GetStreamsResp")
}

func init() { proto.RegisterFile("video.proto", fileDescriptor_0ad4ea8866efb1e3) }

var fileDescriptor_0ad4ea8866efb1e3 = []byte{
	// 473 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x52, 0x4d, 0x6f, 0xda, 0x40,
	0x10, 0x8d, 0x3f, 0x03, 0x63, 0x4c, 0xcd, 0xe6, 0xe2, 0x1e, 0xd2, 0x24, 0x3e, 0xe5, 0x84, 0x54,
	0x1f, 0x7b, 0xa8, 0xe4, 0x3a, 0x88, 0x56, 0x25, 0x89, 0x65, 0xf0, 0x21, 0xa7, 0x6a, 0x65, 0xa6,
	0xad, 0x05, 0x78, 0x91, 0xbd, 0x20, 0xf1, 0x03, 0xfa, 0x43, 0xfa, 0x4f, 0xab, 0x1d, 0x3b, 0xc5,
	0x54, 0xdc, 0x7a, 0xda, 0x9d, 0x9d, 0xf7, 0xe6, 0xbd, 0x99, 0x59, 0x70, 0xf6, 0xc5, 0x12, 0xc5,
	0x78, 0x5b, 0x09, 0x29, 0x98, 0x45, 0x41, 0x10, 0x80, 0xf9, 0x45, 0xe2, 0x86, 0x39, 0x60, 0xac,
	0xf0, 0xe0, 0x6b, 0xb7, 0xda, 0x7d, 0x9f, 0xb9, 0x60, 0xed, 0xf9, 0x7a, 0x87, 0xbe, 0xae, 0xc2,
	0x20, 0x03, 0x48, 0x17, 0xf1, 0x23, 0xd6, 0x35, 0xff, 0x81, 0xec, 0x0d, 0x5c, 0x56, 0x32, 0x5f,
	0x1c, 0xb6, 0xd8, 0xa2, 0xaf, 0xc0, 0xa9, 0xb1, 0xda, 0x17, 0x39, 0xd2, 0x23, 0x71, 0xd8, 0x1d,
	0x0c, 0x2a, 0x99, 0x47, 0x55, 0xc5, 0x0f, 0x0f, 0x5c, 0x72, 0xdf, 0xb8, 0x35, 0xee, 0x9d, 0xd0,
	0x19, 0x37, 0x16, 0x94, 0x64, 0xf0, 0x16, 0x60, 0x8a, 0x32, 0xfe, 0xc9, 0xcb, 0x12, 0xd7, 0xca,
	0xc0, 0xae, 0x58, 0x36, 0x25, 0x83, 0x6b, 0x18, 0x1e, 0x53, 0x29, 0xd6, 0x5b, 0x4a, 0x57, 0xeb,
	0x36, 0x1d, 0x82, 0x3d, 0x97, 0x15, 0xf2, 0xcd, 0x09, 0xeb, 0x15, 0xd3, 0x18, 0x18, 0x82, 0x2d,
	0x45, 0xbe, 0xc2, 0xd2, 0x37, 0x88, 0xf3, 0x4b, 0x87, 0x41, 0x43, 0x8a, 0xf2, 0x1c, 0xeb, 0x9a,
	0x8d, 0xc1, 0xe6, 0xb9, 0x2c, 0x44, 0x49, 0xec, 0x61, 0xf8, 0xae, 0xf5, 0xd6, 0x05, 0x8d, 0x23,
	0x42, 0xa8, 0xbe, 0xd8, 0x7b, 0x85, 0x57, 0x8f, 0x24, 0x30, 0x0c, 0xef, 0xce, 0xe3, 0xd5, 0x11,
	0x8b, 0x52, 0x56, 0x62, 0xcd, 0x46, 0xd0, 0x6f, 0x28, 0xca, 0x63, 0x63, 0xe3, 0x03, 0x40, 0xa7,
	0x26, 0x80, 0x9d, 0x64, 0xb3, 0x59, 0x96, 0x78, 0x17, 0x6c, 0x00, 0xbd, 0xf9, 0xe4, 0xe9, 0xe1,
	0x53, 0x14, 0x7f, 0xf5, 0x34, 0xd6, 0x03, 0x33, 0xc9, 0xe6, 0x9f, 0x3d, 0x9d, 0x6e, 0xb3, 0xe8,
	0xc5, 0x33, 0x82, 0x18, 0xdc, 0xd3, 0xfa, 0x3d, 0x30, 0xb3, 0xf9, 0x24, 0xf5, 0x2e, 0x58, 0x1f,
	0xac, 0x69, 0xfa, 0x9c, 0x25, 0x9e, 0xc6, 0x1c, 0xb8, 0x8c, 0x9f, 0x1f, 0x93, 0xe8, 0xe9, 0xc5,
	0xd3, 0x99, 0x07, 0x83, 0x36, 0xf8, 0xb6, 0x48, 0x27, 0x13, 0xcf, 0x08, 0x7e, 0x6b, 0xd0, 0x9b,
	0xa2, 0x5c, 0x88, 0x15, 0x96, 0xa7, 0xe3, 0x73, 0xc1, 0xda, 0x95, 0x7c, 0x83, 0xc7, 0x01, 0xb6,
	0xf3, 0x31, 0x5e, 0xd3, 0x52, 0x28, 0xb4, 0x49, 0xe1, 0x08, 0xfa, 0xb9, 0xd8, 0x6c, 0x79, 0x79,
	0x28, 0x96, 0xbe, 0xd5, 0x9d, 0xbf, 0xfd, 0xdf, 0x8d, 0x7e, 0x04, 0x97, 0x2c, 0xaa, 0xf5, 0xd1,
	0xf6, 0xff, 0x6a, 0x6b, 0xff, 0xec, 0xf6, 0xac, 0x55, 0xa5, 0x3d, 0x45, 0xd9, 0x2c, 0xa6, 0xee,
	0x36, 0xe9, 0xb2, 0x1b, 0xd0, 0x6b, 0x4e, 0x34, 0x27, 0xbc, 0x3a, 0xb3, 0xc1, 0x20, 0xa1, 0xaf,
	0xd7, 0x72, 0x49, 0xfc, 0x06, 0xcc, 0xa2, 0xfc, 0x2e, 0xa8, 0x80, 0x13, 0x8e, 0x5a, 0x52, 0x47,
	0xe0, 0x1a, 0xec, 0x9a, 0xae, 0xbe, 0x4e, 0xbf, 0xdc, 0x3d, 0xa9, 0xfb, 0x27, 0x00, 0x00, 0xff,
	0xff, 0x16, 0x62, 0x92, 0x33, 0x77, 0x03, 0x00, 0x00,
}
