# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: video.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='video.proto',
  package='video',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x0bvideo.proto\x12\x05video\"\"\n\x04Item\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"@\n\nRTCMessage\x12\x0f\n\x07rtcType\x18\x01 \x01(\t\x12!\n\x0crtcArrayData\x18\x02 \x03(\x0b\x32\x0b.video.Item\"\x19\n\nGetChannel\x12\x0b\n\x03uid\x18\x01 \x01(\r\"\x1d\n\x0eGetChannelResp\x12\x0b\n\x03url\x18\x01 \x01(\t\"\x19\n\nCallClient\x12\x0b\n\x03url\x18\x01 \x01(\t\"*\n\x0e\x43\x61llClientResp\x12\x0b\n\x03res\x18\x01 \x01(\x08\x12\x0b\n\x03url\x18\x02 \x01(\t\"\x12\n\x10\x43\x61llClientCancel')
)




_ITEM = _descriptor.Descriptor(
  name='Item',
  full_name='video.Item',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='video.Item.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='video.Item.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=56,
)


_RTCMESSAGE = _descriptor.Descriptor(
  name='RTCMessage',
  full_name='video.RTCMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rtcType', full_name='video.RTCMessage.rtcType', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rtcArrayData', full_name='video.RTCMessage.rtcArrayData', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=58,
  serialized_end=122,
)


_GETCHANNEL = _descriptor.Descriptor(
  name='GetChannel',
  full_name='video.GetChannel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uid', full_name='video.GetChannel.uid', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=124,
  serialized_end=149,
)


_GETCHANNELRESP = _descriptor.Descriptor(
  name='GetChannelResp',
  full_name='video.GetChannelResp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='url', full_name='video.GetChannelResp.url', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=151,
  serialized_end=180,
)


_CALLCLIENT = _descriptor.Descriptor(
  name='CallClient',
  full_name='video.CallClient',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='url', full_name='video.CallClient.url', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=182,
  serialized_end=207,
)


_CALLCLIENTRESP = _descriptor.Descriptor(
  name='CallClientResp',
  full_name='video.CallClientResp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='res', full_name='video.CallClientResp.res', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='url', full_name='video.CallClientResp.url', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=209,
  serialized_end=251,
)


_CALLCLIENTCANCEL = _descriptor.Descriptor(
  name='CallClientCancel',
  full_name='video.CallClientCancel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=253,
  serialized_end=271,
)

_RTCMESSAGE.fields_by_name['rtcArrayData'].message_type = _ITEM
DESCRIPTOR.message_types_by_name['Item'] = _ITEM
DESCRIPTOR.message_types_by_name['RTCMessage'] = _RTCMESSAGE
DESCRIPTOR.message_types_by_name['GetChannel'] = _GETCHANNEL
DESCRIPTOR.message_types_by_name['GetChannelResp'] = _GETCHANNELRESP
DESCRIPTOR.message_types_by_name['CallClient'] = _CALLCLIENT
DESCRIPTOR.message_types_by_name['CallClientResp'] = _CALLCLIENTRESP
DESCRIPTOR.message_types_by_name['CallClientCancel'] = _CALLCLIENTCANCEL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Item = _reflection.GeneratedProtocolMessageType('Item', (_message.Message,), dict(
  DESCRIPTOR = _ITEM,
  __module__ = 'video_pb2'
  # @@protoc_insertion_point(class_scope:video.Item)
  ))
_sym_db.RegisterMessage(Item)

RTCMessage = _reflection.GeneratedProtocolMessageType('RTCMessage', (_message.Message,), dict(
  DESCRIPTOR = _RTCMESSAGE,
  __module__ = 'video_pb2'
  # @@protoc_insertion_point(class_scope:video.RTCMessage)
  ))
_sym_db.RegisterMessage(RTCMessage)

GetChannel = _reflection.GeneratedProtocolMessageType('GetChannel', (_message.Message,), dict(
  DESCRIPTOR = _GETCHANNEL,
  __module__ = 'video_pb2'
  # @@protoc_insertion_point(class_scope:video.GetChannel)
  ))
_sym_db.RegisterMessage(GetChannel)

GetChannelResp = _reflection.GeneratedProtocolMessageType('GetChannelResp', (_message.Message,), dict(
  DESCRIPTOR = _GETCHANNELRESP,
  __module__ = 'video_pb2'
  # @@protoc_insertion_point(class_scope:video.GetChannelResp)
  ))
_sym_db.RegisterMessage(GetChannelResp)

CallClient = _reflection.GeneratedProtocolMessageType('CallClient', (_message.Message,), dict(
  DESCRIPTOR = _CALLCLIENT,
  __module__ = 'video_pb2'
  # @@protoc_insertion_point(class_scope:video.CallClient)
  ))
_sym_db.RegisterMessage(CallClient)

CallClientResp = _reflection.GeneratedProtocolMessageType('CallClientResp', (_message.Message,), dict(
  DESCRIPTOR = _CALLCLIENTRESP,
  __module__ = 'video_pb2'
  # @@protoc_insertion_point(class_scope:video.CallClientResp)
  ))
_sym_db.RegisterMessage(CallClientResp)

CallClientCancel = _reflection.GeneratedProtocolMessageType('CallClientCancel', (_message.Message,), dict(
  DESCRIPTOR = _CALLCLIENTCANCEL,
  __module__ = 'video_pb2'
  # @@protoc_insertion_point(class_scope:video.CallClientCancel)
  ))
_sym_db.RegisterMessage(CallClientCancel)


# @@protoc_insertion_point(module_scope)
