// Code generated by protoc-gen-go. DO NOT EDIT.
// source: penetrate.proto

package conn_penetrate

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Penetrate_TargetType int32

const (
	Penetrate_USER         Penetrate_TargetType = 0
	Penetrate_GROUP        Penetrate_TargetType = 1
	Penetrate_COMPANY      Penetrate_TargetType = 2
	Penetrate_COMPANY_TREE Penetrate_TargetType = 3
)

var Penetrate_TargetType_name = map[int32]string{
	0: "USER",
	1: "GROUP",
	2: "COMPANY",
	3: "COMPANY_TREE",
}

var Penetrate_TargetType_value = map[string]int32{
	"USER":         0,
	"GROUP":        1,
	"COMPANY":      2,
	"COMPANY_TREE": 3,
}

func (x Penetrate_TargetType) Enum() *Penetrate_TargetType {
	p := new(Penetrate_TargetType)
	*p = x
	return p
}

func (x Penetrate_TargetType) String() string {
	return proto.EnumName(Penetrate_TargetType_name, int32(x))
}

func (x *Penetrate_TargetType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Penetrate_TargetType_value, data, "Penetrate_TargetType")
	if err != nil {
		return err
	}
	*x = Penetrate_TargetType(value)
	return nil
}

func (Penetrate_TargetType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_554feee40cfca45f, []int{1, 0}
}

// 用于封装不同的需要发送到客户端的消息
type UserMessage struct {
	Name                 *string  `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Msg                  []byte   `protobuf:"bytes,2,opt,name=msg" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserMessage) Reset()         { *m = UserMessage{} }
func (m *UserMessage) String() string { return proto.CompactTextString(m) }
func (*UserMessage) ProtoMessage()    {}
func (*UserMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_554feee40cfca45f, []int{0}
}

func (m *UserMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserMessage.Unmarshal(m, b)
}
func (m *UserMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserMessage.Marshal(b, m, deterministic)
}
func (m *UserMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserMessage.Merge(m, src)
}
func (m *UserMessage) XXX_Size() int {
	return xxx_messageInfo_UserMessage.Size(m)
}
func (m *UserMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_UserMessage.DiscardUnknown(m)
}

var xxx_messageInfo_UserMessage proto.InternalMessageInfo

func (m *UserMessage) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *UserMessage) GetMsg() []byte {
	if m != nil {
		return m.Msg
	}
	return nil
}

// 透传协议消息
type Penetrate struct {
	Tartype              *Penetrate_TargetType `protobuf:"varint,1,opt,name=tartype,enum=conn.penetrate.Penetrate_TargetType" json:"tartype,omitempty"`
	Targets              *uint32               `protobuf:"varint,2,opt,name=targets" json:"targets,omitempty"`
	Msg                  []*UserMessage        `protobuf:"bytes,3,rep,name=msg" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *Penetrate) Reset()         { *m = Penetrate{} }
func (m *Penetrate) String() string { return proto.CompactTextString(m) }
func (*Penetrate) ProtoMessage()    {}
func (*Penetrate) Descriptor() ([]byte, []int) {
	return fileDescriptor_554feee40cfca45f, []int{1}
}

func (m *Penetrate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Penetrate.Unmarshal(m, b)
}
func (m *Penetrate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Penetrate.Marshal(b, m, deterministic)
}
func (m *Penetrate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Penetrate.Merge(m, src)
}
func (m *Penetrate) XXX_Size() int {
	return xxx_messageInfo_Penetrate.Size(m)
}
func (m *Penetrate) XXX_DiscardUnknown() {
	xxx_messageInfo_Penetrate.DiscardUnknown(m)
}

var xxx_messageInfo_Penetrate proto.InternalMessageInfo

func (m *Penetrate) GetTartype() Penetrate_TargetType {
	if m != nil && m.Tartype != nil {
		return *m.Tartype
	}
	return Penetrate_USER
}

func (m *Penetrate) GetTargets() uint32 {
	if m != nil && m.Targets != nil {
		return *m.Targets
	}
	return 0
}

func (m *Penetrate) GetMsg() []*UserMessage {
	if m != nil {
		return m.Msg
	}
	return nil
}

type ClientMessageIn struct {
	Uid                  *uint32  `protobuf:"varint,1,opt,name=uid" json:"uid,omitempty"`
	Name                 *string  `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Msg                  []byte   `protobuf:"bytes,3,opt,name=msg" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClientMessageIn) Reset()         { *m = ClientMessageIn{} }
func (m *ClientMessageIn) String() string { return proto.CompactTextString(m) }
func (*ClientMessageIn) ProtoMessage()    {}
func (*ClientMessageIn) Descriptor() ([]byte, []int) {
	return fileDescriptor_554feee40cfca45f, []int{2}
}

func (m *ClientMessageIn) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientMessageIn.Unmarshal(m, b)
}
func (m *ClientMessageIn) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientMessageIn.Marshal(b, m, deterministic)
}
func (m *ClientMessageIn) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientMessageIn.Merge(m, src)
}
func (m *ClientMessageIn) XXX_Size() int {
	return xxx_messageInfo_ClientMessageIn.Size(m)
}
func (m *ClientMessageIn) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientMessageIn.DiscardUnknown(m)
}

var xxx_messageInfo_ClientMessageIn proto.InternalMessageInfo

func (m *ClientMessageIn) GetUid() uint32 {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return 0
}

func (m *ClientMessageIn) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *ClientMessageIn) GetMsg() []byte {
	if m != nil {
		return m.Msg
	}
	return nil
}

type ExternalServMsg struct {
	Msg                  *string  `protobuf:"bytes,1,opt,name=msg" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExternalServMsg) Reset()         { *m = ExternalServMsg{} }
func (m *ExternalServMsg) String() string { return proto.CompactTextString(m) }
func (*ExternalServMsg) ProtoMessage()    {}
func (*ExternalServMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_554feee40cfca45f, []int{3}
}

func (m *ExternalServMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExternalServMsg.Unmarshal(m, b)
}
func (m *ExternalServMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExternalServMsg.Marshal(b, m, deterministic)
}
func (m *ExternalServMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExternalServMsg.Merge(m, src)
}
func (m *ExternalServMsg) XXX_Size() int {
	return xxx_messageInfo_ExternalServMsg.Size(m)
}
func (m *ExternalServMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_ExternalServMsg.DiscardUnknown(m)
}

var xxx_messageInfo_ExternalServMsg proto.InternalMessageInfo

func (m *ExternalServMsg) GetMsg() string {
	if m != nil && m.Msg != nil {
		return *m.Msg
	}
	return ""
}

type SendMMS struct {
	Title                *string  `protobuf:"bytes,1,opt,name=title" json:"title,omitempty"`
	Content              *string  `protobuf:"bytes,2,opt,name=content" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendMMS) Reset()         { *m = SendMMS{} }
func (m *SendMMS) String() string { return proto.CompactTextString(m) }
func (*SendMMS) ProtoMessage()    {}
func (*SendMMS) Descriptor() ([]byte, []int) {
	return fileDescriptor_554feee40cfca45f, []int{4}
}

func (m *SendMMS) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendMMS.Unmarshal(m, b)
}
func (m *SendMMS) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendMMS.Marshal(b, m, deterministic)
}
func (m *SendMMS) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendMMS.Merge(m, src)
}
func (m *SendMMS) XXX_Size() int {
	return xxx_messageInfo_SendMMS.Size(m)
}
func (m *SendMMS) XXX_DiscardUnknown() {
	xxx_messageInfo_SendMMS.DiscardUnknown(m)
}

var xxx_messageInfo_SendMMS proto.InternalMessageInfo

func (m *SendMMS) GetTitle() string {
	if m != nil && m.Title != nil {
		return *m.Title
	}
	return ""
}

func (m *SendMMS) GetContent() string {
	if m != nil && m.Content != nil {
		return *m.Content
	}
	return ""
}

func init() {
	proto.RegisterEnum("conn.penetrate.Penetrate_TargetType", Penetrate_TargetType_name, Penetrate_TargetType_value)
	proto.RegisterType((*UserMessage)(nil), "conn.penetrate.UserMessage")
	proto.RegisterType((*Penetrate)(nil), "conn.penetrate.Penetrate")
	proto.RegisterType((*ClientMessageIn)(nil), "conn.penetrate.ClientMessageIn")
	proto.RegisterType((*ExternalServMsg)(nil), "conn.penetrate.ExternalServMsg")
	proto.RegisterType((*SendMMS)(nil), "conn.penetrate.SendMMS")
}

func init() { proto.RegisterFile("penetrate.proto", fileDescriptor_554feee40cfca45f) }

var fileDescriptor_554feee40cfca45f = []byte{
	// 323 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x90, 0xcf, 0x4f, 0xfa, 0x40,
	0x10, 0xc5, 0xbf, 0xa5, 0x10, 0xbe, 0x0c, 0xbf, 0x9a, 0x89, 0x07, 0x12, 0x63, 0x24, 0xe8, 0x81,
	0x8b, 0x3d, 0xe0, 0xc9, 0x8b, 0x51, 0x49, 0x63, 0x38, 0x54, 0xc8, 0x16, 0x0e, 0x9e, 0xcc, 0xa6,
	0x4c, 0x4a, 0x93, 0xb2, 0x6d, 0x76, 0x47, 0x23, 0xff, 0xa8, 0x7f, 0x8f, 0x69, 0x4b, 0x41, 0xf1,
	0x36, 0x6f, 0x33, 0xef, 0xbd, 0x9d, 0x0f, 0xf4, 0x33, 0x52, 0xc4, 0x5a, 0x32, 0xb9, 0x99, 0x4e,
	0x39, 0xc5, 0x5e, 0x98, 0x2a, 0xe5, 0x1e, 0x5e, 0x47, 0xb7, 0xd0, 0x5e, 0x19, 0xd2, 0x3e, 0x19,
	0x23, 0x23, 0x42, 0x84, 0xba, 0x92, 0x5b, 0x1a, 0x58, 0x43, 0x6b, 0xdc, 0x12, 0xc5, 0x8c, 0x0e,
	0xd8, 0x5b, 0x13, 0x0d, 0x6a, 0x43, 0x6b, 0xdc, 0x11, 0xf9, 0x38, 0xfa, 0xb2, 0xa0, 0xb5, 0xa8,
	0x22, 0xf0, 0x1e, 0x9a, 0x2c, 0x35, 0xef, 0xb2, 0xd2, 0xd6, 0x9b, 0x5c, 0xbb, 0xbf, 0x4b, 0xdc,
	0xc3, 0xae, 0xbb, 0x94, 0x3a, 0x22, 0x5e, 0xee, 0x32, 0x12, 0x95, 0x09, 0x07, 0x85, 0x3f, 0x22,
	0x36, 0x45, 0x47, 0x57, 0x54, 0x12, 0x6f, 0xca, 0x66, 0x7b, 0x68, 0x8f, 0xdb, 0x93, 0xf3, 0xd3,
	0xd4, 0x1f, 0xff, 0x2e, 0xbf, 0xf5, 0x00, 0x70, 0xcc, 0xc7, 0xff, 0x50, 0x5f, 0x05, 0x9e, 0x70,
	0xfe, 0x61, 0x0b, 0x1a, 0xcf, 0x62, 0xbe, 0x5a, 0x38, 0x16, 0xb6, 0xa1, 0x39, 0x9d, 0xfb, 0x8b,
	0xc7, 0x97, 0x57, 0xa7, 0x86, 0x0e, 0x74, 0xf6, 0xe2, 0x6d, 0x29, 0x3c, 0xcf, 0xb1, 0x47, 0x33,
	0xe8, 0x4f, 0x93, 0x98, 0x14, 0xef, 0x73, 0x67, 0x2a, 0xbf, 0xfe, 0x3d, 0x5e, 0x17, 0x97, 0x75,
	0x45, 0x3e, 0x1e, 0x18, 0xd5, 0xfe, 0x32, 0xb2, 0x8f, 0x8c, 0xae, 0xa0, 0xef, 0x7d, 0x32, 0x69,
	0x25, 0x93, 0x80, 0xf4, 0x87, 0x6f, 0xa2, 0x6a, 0xa9, 0x64, 0x5b, 0x2c, 0xdd, 0x41, 0x33, 0x20,
	0xb5, 0xf6, 0xfd, 0x00, 0xcf, 0xa0, 0xc1, 0x31, 0x27, 0x15, 0xfa, 0x52, 0xe4, 0x6c, 0xc2, 0x54,
	0x31, 0x29, 0xde, 0xd7, 0x55, 0xf2, 0xe9, 0x12, 0x2e, 0xc2, 0x74, 0xeb, 0x9a, 0x8d, 0x54, 0x49,
	0xcc, 0x14, 0x6e, 0x4e, 0xf0, 0x7c, 0x07, 0x00, 0x00, 0xff, 0xff, 0xf0, 0xa3, 0x1e, 0x14, 0xfb,
	0x01, 0x00, 0x00,
}
